### ISSUE TITLE
Add a way to specify to use a system on "all" scenes in systems.json

### ISSUE THREAD

**Issue by AlexBezuska** [SplatJS/splat-ecs#35]
This would be really useful when many of your game's scenes use all of the same systems.

**Comment by CaldwellYSR** [comment]
#39 This works with the caveat of not allowing a scene named "all" to have a system that only runs on that scene.

```
{                                                                                                                      
     "name": "splat-ecs/lib/systems/advance-timers",                                                                    
        "scenes": [                                                                                                        
            "", "all"                                                                                                          
        ]                                                                                                             
}
```

This is the only way I can think to have a system that only runs on a scene named "all" but I think we can just tell users not to use the scene name "all"

**Comment by ericlathrop** [comment]
What if instead of an array of scene names if we encounter a string "all", then use it on all scenes? That way you can still have a scene named "all".

**Comment by CaldwellYSR** [comment]
Obvious answer is obvious... I've updated the PR

**Comment by ericlathrop** [comment]
Thanks!
