### ISSUE TITLE
Gamepad Support seems to cause break in Safari (iOS and Desktop)

### ISSUE THREAD

**Issue by CaldwellYSR** [SplatJS/splat-ecs#38]
On iOS Safari my game [my game](http://caldwellysr.github.io/SplishSplashClone/build/) doesn't work and it gives me the following error in index.js.

`TypeError: navigator.getGamepads is not a function. (In 'navigator.getGamepads()', 'navigator.getGamepads' is undefined)`

Desktop gives the same error as well as 2 other global errors but I think they're unrelated. 

Desktop Safari version 9.0.3 (11601.4.4)
iOS version 9.3

**Comment by ericlathrop** [comment]
Thanks for finding this! I don't have safari, and was wondering why my last game didn't work on an iPhone. This issue is really in https://github.com/ericlathrop/html5-gamepad but I'll leave this issue open as a reminder to update it when the library is patched.
