### ISSUE TITLE
Make it possible to pass initial arguments into a scene from scenes.json

### ISSUE THREAD

**Issue by CaldwellYSR** [SplatJS/splat-ecs#41]
From what I can see [here](https://github.com/CaldwellYSR/splat-ecs/blob/master/lib/game.js#L62) the `sceneArgs` object is always empty on the initial call of `makeScene`. Would it make sense for "global" scene config to allow an `arguments` object in `scenes.json` that gets read there? Is there already another way to do this outside of `scenes.json` that I'm not thinking about?

**Comment by ericlathrop** [comment]
I'm not sure what this would solve. I think you should just have a default set of arguments if none are passed in. I do something like `var level = game.arguments.level || 1`.
