### ISSUE TITLE
Make scaled viewport dimensions as easily accessible as canvas width/height

### ISSUE THREAD

**Issue by benwiley4000** [SplatJS/splat-ecs#5]
When working on a game that frequently zooms in and out and draws objects at a resolution that doesn't match the canvas resolution 1:1, it's necessary to have ready access to the resolution data for the viewport, including dimensions and/or scale (one can be derived from the other, I guess). To have this info easily accessible through the scene data object would dramatically reduce headaches and the need to calculate such things on the fly...

**Comment by ericlathrop** [comment]
By "resolution data for the viewport" do you mean `canvas.width` and `canvas.height`, or the camera's width and height?

**Comment by benwiley4000** [comment]
The camera width/height might actually be what I am looking for?

**Comment by ericlathrop** [comment]
The game's display is scaled to the camera's size. [See here.](https://github.com/SplatJS/splat-ecs/blob/master/lib/systems/viewport.js#L11)

**Comment by benwiley4000** [comment]
Thanks, this is probably what I needed.

**Comment by ericlathrop** [comment]
Sweet!
