### ISSUE TITLE
Apply Shake Reset Initial Position

### ISSUE THREAD

**Issue by CaldwellYSR** [SplatJS/splat-ecs#57]
Should ApplyShake reset the object to it's initial position after the duration is up? When I try to use ApplyShake on an entity it can get moved around the screen. I'm currently using a script to reset them.

**Comment by ericlathrop** [comment]
Did you also add the "revert-shake" system to the end of the renderers section? That puts the position back.

**Comment by CaldwellYSR** [comment]
Ah... well that makes sense.

**Comment by CaldwellYSR** [comment]
Revert Shake actually made it worse... it's putting the object at 0,0 after a shake is applied

**Comment by ericlathrop** [comment]
Both systems belong in the renderer section. Apply shake should be the very first, and revert shake should be the very last.

**Comment by CaldwellYSR** [comment]
I didn't realize they were both renderers
